# machine learning

## KNN: K-최근접 이웃 분류(K-Nearest Neighbor)

In [1]:
import numpy as np

In [3]:
# 키, 학생분류
x = [140, 150, 160, 170, 180]
y = [0, 0, 1, 1, 2] # 초:0 중:1 고:2

x_test = [120, 158, 177]

In [9]:
x = np.array(x).reshape((-1, 1)) # 1d를 2d로 변경, -1 자동
y = np.array(y)
x.shape

(5, 1)

In [11]:
x_test = np.array(x_test).reshape((-1, 1))
x_test.shape

(3, 1)

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
model = KNeighborsClassifier(n_neighbors=1) # 객체 만들기, shitf+tab 설명
model # 객체 정보 보기

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [10]:
model.fit(x, y) # 모델을 fitting(학습)시켜라

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [12]:
model.predict(x_test)

array([0, 1, 2])

결과: 120:초 158:중 177:고

In [21]:
# 동물분류 새:0,개:1, 말:2
# 특징 [다리 갯수, 털 길이 cm]

x = [[2,7.0], [2, 4.0], [4, 10.0], [4, 9.0], [4, 3.0], [4, 5.0]]
y = [0, 0, 1, 1, 2, 2]

x_test = [[2,9], [4, 4]]

위의 데이터를 KNN 모델을 이용해 x_test를 예측하세요.

In [22]:
model = KNeighborsClassifier(n_neighbors=3)
model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [23]:
model.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [24]:
model.predict(x_test)

array([1, 2])

기대값: [0, 2] # 새, 말  
결과값: [1, 2] # 개, 말

## reshape 연습

In [15]:
a = np.arange(9)
a, a.shape, a.ndim

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), (9,), 1)

In [17]:
np.reshape(a, (1,3,3))

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [20]:
np.reshape(a, (-1,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [19]:
np.reshape(a, (-1,2)) # 소수점이 올 수 없다

ValueError: cannot reshape array of size 9 into shape (2)

In [18]:
np.reshape(a, (-1,-1)) # 가능성이 여러개

ValueError: can only specify one unknown dimension

list: 데이터 저장, 관리용  
array: 연산용

In [25]:
a = [1,2,3]
a, type(a)

([1, 2, 3], list)

In [27]:
a.append(4)
a
a.insert(1,100)
a

[1, 100, 2, 3, 4, 4]

In [28]:
aa = np.array(a)
aa

array([  1, 100,   2,   3,   4,   4])

In [29]:
a+a

[1, 100, 2, 3, 4, 4, 1, 100, 2, 3, 4, 4]

In [30]:
aa+aa

array([  2, 200,   4,   6,   8,   8])