키 데이터 파일을 읽어서 KNN 분류기를 이용해 테스트 셋을 예측해봅니다.

In [21]:
# 부모님 키에 따른 자식의 키 예측
# 회귀문제 : Y가 실수
# CSV(Comma Serate Value) 콤마로 값을 분리
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor

In [2]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 825E-D1B2

 C:\Users\admin\Documents\Python Scripts\Tensorflow 디렉터리

2020-01-23  오전 11:26    <DIR>          .
2020-01-23  오전 11:26    <DIR>          ..
2020-01-23  오전 11:26    <DIR>          .ipynb_checkpoints
2020-01-23  오전 11:26            14,448 01_KNN.ipynb
2020-01-23  오전 11:25                72 02_KNN-CSV.ipynb
2020-01-23  오전 11:24               228 height.csv
               3개 파일              14,748 바이트
               3개 디렉터리  922,898,169,856 바이트 남음


In [6]:
df = pd.read_csv("height.csv")
df.head()

mother  father  child
0     160     170    172
1     172     188    195
2     155     166    167
3     164     175    174
4     159     169    173

In [7]:
df.shape

(8, 3)

In [8]:
x_test = [[160, 172], [155,177]] # 이 데이터의 자식의 키를 KNN으로 예측하세요

In [ ]:
x = df[['mother', 'father']]
y = df['child']
# x = np.array(x)
x = x.values
# y = np.array(y)
y = y.values

In [37]:
x = df.iloc[:-2,:2]
x, type(x)

(   mother  father
 0     160     170
 1     172     188
 2     155     166
 3     164     175
 4     159     169
 5     173     180, pandas.core.frame.DataFrame)

In [38]:
x = np.array(x)
x

array([[160, 170],
       [172, 188],
       [155, 166],
       [164, 175],
       [159, 169],
       [173, 180]], dtype=int64)

In [39]:
y = df.iloc[:-2,-1:]
y

child
0    172
1    195
2    167
3    174
4    173
5    185

In [40]:
y = np.array(y)
y

array([[172],
       [195],
       [167],
       [174],
       [173],
       [185]], dtype=int64)

In [41]:
model = KNeighborsRegressor(n_neighbors=2)
model

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=2, p=2,
          weights='uniform')

In [42]:
model.fit(x,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=2, p=2,
          weights='uniform')

In [43]:
model.predict(x_test)

array([[ 172.5],
       [ 172.5]])

[160, 172] => 175.0  
[155, 177] => 177.5