선형 함수를 이용하는 선형 모델로 학습시켜서 테스트셋의 자식 키를 예측해봅시다.

- y = ax + b
- y: 자식의 키, x : [어머니 키, 아버지 키] = [x0, x1]
- y = x0 * w0 + x1 * w1 + b
- 자식의 키 = w0 * 어머니 키 + w1 * 아버지 키 + b
- w0 = 0.4, w1 = 0.6, b = 3 가정해보면
- 자식의 키 = 0.4어머니 키 + 0.6 아버지 키 + 3(세대 간의 평균 키 차이)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("height.csv")
df.head(2)

mother  father  child
0     160     170    172
1     172     188    195

In [3]:
x = df[["mother", "father"]]
y = df["child"]

In [4]:
x = x.values
y = y.values

In [5]:
from sklearn.linear_model import LinearRegression

In [6]:
model = LinearRegression()

In [7]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

$
y = w_0 * x_0 + w_1 * x_1 + b
$

In [8]:
model.coef_, model.intercept_ # 계수와 절편 weight, bias

(array([-0.20984588,  1.34628051]), -22.449161632699202)

In [14]:
# y = w0 * x0 + w1 * x1 + b
h = np.sum(model.coef_ * x, axis=1, keepdims=True) + model.intercept_
h

array([[ 172.84318485],
       [ 194.55808352],
       [ 168.5072922 ],
       [ 178.7352039 ],
       [ 171.70675022],
       [ 183.57799356],
       [ 173.26287661],
       [ 177.80861514]])

In [13]:
y

array([172, 195, 167, 174, 173, 185, 178, 177], dtype=int64)

성능 측정
- 오차가 얼마나 나는가?

In [18]:
np.mean(np.abs(np.squeeze(h) - y)) # squeeze 차원이 1이면 제거, 축소

1.9735740228457423

In [21]:
# metrics 지표
from sklearn.metrics import mean_absolute_error # 평균 절대 오차
from sklearn.metrics import r2_score # 결정계수, 1: 완벽, 0:보통, 음수:엉망

In [23]:
mean_absolute_error(y, h), r2_score(y, h) # 1에 가까우므로 예측이 잘 되었다고 볼 수 있다.

(1.9735740228457423, 0.90223628571239056)