# 분류: Classification

클래스가 2개 뿐인 2진(binary) 분류를 해봅시다.

1: 관심 타겟 (더 적은 샘플)
0: 관심 없는 클래스 (더 흔하고 많은 샘플)

암환자 분류 : 0-정상 1-암환자  
사기 검출 : 0-정상 1-사기  
타이타닉 : 0-사망자 1-생존자

In [1]:
import numpy as np

목표: 혈액혁 예측하기 (A, B)  
A형 특징 : 배려심, 막연한 걱정  
B형 특징 : 용기, 기분파

In [ ]:
판단력, 사회성

In [2]:
# [판단력, 사회성]
x = [[50, 90], [80, 50]]
y = [0, 1]

In [3]:
x = np.array(x)
y = np.array(y)

In [4]:
from sklearn.linear_model import LogisticRegression # 논리 회귀 + sigmoid

In [5]:
model = LogisticRegression().fit(x,y)

In [6]:
model.predict(x)

array([0, 1])

모델 분석
- 판단력이 1 오르면 B형일 확률이 0.16 증가
- 사회성이 1 오르면 B형일 확률이 0.14 감소

In [7]:
model.coef_, model.intercept_

(array([[ 0.16068743, -0.1498761 ]]), array([ 0.0004109]))

In [11]:
np.sum(model.coef_ * x + model.intercept_, axis=1) > 0

array([False,  True], dtype=bool)

True = B형

In [12]:
from sklearn.datasets import load_iris # 붓꽃 데이터

In [13]:
x, y = load_iris(return_X_y=True)

In [14]:
x.shape, y.shape

((150, 4), (150,))

In [23]:
x = x[:100]
y = y[:100]

In [27]:
model = LogisticRegression().fit(x,y)

In [28]:
model.score(x,y)

1.0

In [29]:
model.coef_, model.intercept_

(array([[-0.40731745, -1.46092371,  2.24004724,  1.00841492]]),
 array([-0.26048137]))

In [32]:
# 마지막으로 0보다 크냐(후처리)로 최종 판정
np.sum(model.coef_ * x + model.intercept_, axis=1) > 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)