## stack, concatenate, reshape, indexing

In [1]:
import numpy as np

### stack : 배열들을 하나로 쌓는다.
(차원이 1 증가한다)

In [3]:
a = np.arange(12).reshape(3,4)
b = a
c = np.stack((a,b), axis=0)
c, c.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]), (2, 3, 4))

In [4]:
c = np.stack((a,b), axis=1)
c, c.shape

(array([[[ 0,  1,  2,  3],
         [ 0,  1,  2,  3]],
 
        [[ 4,  5,  6,  7],
         [ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11],
         [ 8,  9, 10, 11]]]), (3, 2, 4))

In [5]:
c = np.stack((a,b), axis=2)
c, c.shape

(array([[[ 0,  0],
         [ 1,  1],
         [ 2,  2],
         [ 3,  3]],
 
        [[ 4,  4],
         [ 5,  5],
         [ 6,  6],
         [ 7,  7]],
 
        [[ 8,  8],
         [ 9,  9],
         [10, 10],
         [11, 11]]]), (3, 4, 2))

### concatenate:concat (잇다, 붙이다)
(차원이 증가하지 않는다)

In [6]:
a = np.arange(12).reshape(3,4)
b = a
c = np.concatenate((a,b), axis=0)
c, c.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), (6, 4))

In [9]:
c = np.concatenate((a,b), axis=1)
c, c.shape

(array([[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]]), (3, 8))

### reshape : 모양 바꾸기
-1 은 자동계산

In [11]:
a = np.arange(12).reshape(3,4)
c = a.reshape((2,6))

a.shape, c.shape

((3, 4), (2, 6))

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [15]:
c = a.reshape((-1, 3))
c, c.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), (4, 3))

### indexing : 데이터 뽑기
-1 은 뒤에서부터 인덱싱하기

In [16]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a[0]

array([0, 1, 2, 3])

In [18]:
a[1]

array([4, 5, 6, 7])

In [20]:
a[-2]

array([4, 5, 6, 7])

###  slicing : 데이터 자르기
[시작 : 끝]

In [21]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a[0:2, 1:2]

array([[1],
       [5]])

In [24]:
a[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])